baseURL = 'https://brentonmallen.com/'
languageCode = 'en-us'
title = 'Brenton Mallen'
theme = 'hugo-coder'
defaultcontentlanguage = "en"
googleAnalytics = "G-9QF85MHBL7"

paginate = 10

[params]
  author = "Brenton Mallen"
  info = "Machine Learning Engineer"
  avatarURL = "images/avatar/avatar.jpeg"
  faviconSVG = "images/logos/logo.svg"
  faviconSVGLight = "images/logos/logo.svg"
  faviconSVGDark = "images/logos/logo-dark.svg"
  colorScheme = "auto"
  since = "2015"
  titleImage = "images/logos/logo.svg"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/brentonmallen1"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/brentonmallen/"

[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/brentonmallen/"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:brenton@mallen.us"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects"

[[menu.main]]
  name = "Resume"
  weight = 3
  url = "about/resume"

[[menu.main]]
  name = "Publications"
  weight = 4
  url = "publications/pubs_and_pres"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
