baseURL = 'https://brentonmallen.com/'
languageCode = 'en-us'
title = 'Brenton Mallen'
theme = 'hugo-coder'
defaultcontentlanguage = "en"
googleAnalytics = "G-9QF85MHBL7"

[pagination]
  pagerSize = 10

[params]
  author = "Brenton Mallen"
  info = "Machine Learning Engineer"
  avatarURL = "images/avatar/avatar.jpeg"
  faviconSVG = "images/logos/logo.svg"
  faviconSVGLight = "images/logos/logo.svg"
  faviconSVGDark = "images/logos/logo-dark.svg"
  colorScheme = "auto"
  since = "2015"
  titleImage = "images/logos/logo.svg"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/brentonmallen1"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/brentonmallen/"

# TODO: replace with cheverto or pixelfed
#[[params.social]]
#  name = "Instagram"
#  icon = "fa fa-instagram fa-2x"
#  weight = 3
#  url = "https://www.instagram.com/brentonmallen/"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:brenton@mallen.us"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects"

[[menu.main]]
  name = "Resume"
  weight = 3
  url = "about/resume"

[[menu.main]]
  name = "Publications"
  weight = 4
  url = "publications/pubs_and_pres"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
      [markup.goldmark.renderHooks.link]
        enableDefault = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
